- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_01_Lab1_Ex2_Mitigate_Attacks.md
•	Module 1 - Lab 1 - Exercise 1:  
o	You must be in Settings>Endpoints to access Device management
o	You must be in Settings>Endpoints to access Roles.
o	You must be in Settings>Endpoints to access Device groups.
•	Module 5 - Lab 1 - Exercise 1 
o	Create a new workspace in Azure Sentinel uses the + Create button, not + Add
[Change_log_SC200_July2021.docx](https://github.com/MicrosoftLearning/SC-200T00A-Microsoft-Security-Operations-Analyst/files/6889506/Change_log_SC200_July2021.docx)
-
-
-
> Updates to instructions due to portal changes and for clarification

- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
bolded the Do Not Run
Fixes # .
-
-
-
> Module 4 Lab 1

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_01_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Threat_Intel.md
> Updates to Labs for Modules 1-6

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Workbooks.md
- index.md
Changed SignInLogs for AuditLogs queries (M7Ex3) and workbooks (M7Ex8). 
Added code snippets (M5Ex1) and notes (M7Ex6) for some statements.
> MTT Lab Updates

- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Threat_Intel.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex4_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex5_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Workbooks.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
Renamed Azure Sentinel with Microsoft Sentinel
> Microsoft Sentinel rebranding

- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
**Link related Github Issue** 🢂 Fixes #57, #62 and #65.
M02-EX01: VM not showing in Device list and Device Group
- Added the docs recommendation to wait until 1 hour to show in device list
- Added a workaround to display the device by adding None to the OS Version filter
M04-EX01: Enhanced queries
- Set the SecurityEvents to 1h query to get fewer results
- Removed the SecurityAlerts table in some queries since it was not showing results
> Enhancements to M2 and M4 Labs

- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex5_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Workbooks.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
**Link related Github Issue** 🢂 Fixes #70  . 
- Fixed issue with B2ms size not available in some regions
- Fixed typos
- Fixed portal updates
> M06-EX02: VM size fix + typos and portal updates

- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
**Updated instructions "M02-LAB01-Exercise 1: Manage incident interface changes**
- [ x] Tested it
- Updated Task 1, steps 9 and 10
-
-
> Updated instructions to match interface changes

- Allfiles/SC200_module4_KQL_scripts.txt
**Module 4 lab text file needed update**
**Link related Github Issue** 🢂 Fixes # 79. [(Include issue number after #)](https://github.com/MicrosoftLearning/SC-200T00A-Microsoft-Security-Operations-Analyst/issues/79)
- Synced KQL text file with lab instructions
-
-
> Aligned module 4 KQL text file with lab instructions

- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
** Lab 04 Exercise 01 Create queries for Microsoft Sentinel using Kusto Query Language (KQL)**
**Link related Github Issue** 🢂 Fixes # 81. (Include issue number after #)
- Modified instructions to reflect UI change
-
-
> Updated instructions per UI change

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
**Updated Lab 01 Exercise 01 Explore Microsoft 365 Defender**
**Link related Github Issue** 🢂 Fixes #83 
Modified lab steps to match portal update
-
-
-
> Updated Lab1_Ex1 per portal changes

- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
**Updated Lab 07 Exercises 1, 2, and 3 per naming, title, and process changes**
**Link related Github Issue** 🢂 Fixes #84, #85, #86 .
- Changed alert rule name to Microsoft Defender for Cloud
- Changed Logic App connector name Microsoft Sentinel alert
- Changed AAD add user role process
-
> Updated Lab 07 exercises

- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
**Updated Lab 08 Exercise 2 wording**
**Link related Github Issue** 🢂 Fixes #87
- Changed wording in lab to match UI
-
-
> Updated per issue #87. Wording change.

- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
Updated instructions for enabling Microsoft Defender for Cloud connector to indicate it is a slider switch not a button.
-
-
-
> Update Lab6 Ex 1 Task 4

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
**Link related Github Issue** 🢂 Fixes #95. 
- Updated GUI change in the M365 Defender portal
> M01-EX01: Fixing M365 Defender preset policies GUI update

- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
**Link related Github Issue** 🢂 Fixes #99.
- Updated KQL statements
> M04-LAB01: Updated KQL statements

- .vscode/settings.json
- Allfiles/SC200_module4_KQL_scripts.txt
- Allfiles/SC200_module7_ASIM_Parser_scripts.txt
- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/01-mitigate-threats-defender-for-endpoint.md
- Instructions/VTD_Demos/02-mitigate-threats-365-defender-azure-defender.md
- Instructions/VTD_Demos/03-create-queries-for-azure-sentinel-using-kql.md
- Instructions/VTD_Demos/04-configure-your-azure-sentinel-environment.md
- Instructions/VTD_Demos/05-create-detections-perform-investigations-azure-sentinel.md
- Instructions/VTD_Demos/06-perform-threat-hunting-azure-sentinel.md
**Updates to VTD demos an a fix to SC-200 Module 7 lab 9. Added an ASIM parser text file**
- ASIM parser text file
- VTD prerequisites demo file
- Other VTD demo file updates
> PR to add ASIM parser text file for Lab 7 ex 9 and VTD demo file updates

- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/02-mitigate-threats-defender-for-endpoint.md
- Instructions/VTD_Demos/03-mitigate-threats-defender-cloud.md
- Instructions/VTD_Demos/04-create-queries-for-microsoft-sentinel-using-kql.md
- Instructions/VTD_Demos/05-configure-your-microsoft-sentinel-environment.md
- Instructions/VTD_Demos/06-create-detections-perform-investigations-microsoft-sentinel.md
- Instructions/VTD_Demos/07-perform-threat-hunting-microsoft-sentinel.md
Renumbered VTD demos to match modules
N/A
- Renumber demo titles to match modules
-
-
> Updated VTD demo instructions

- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/02-mitigate-threats-defender-for-endpoint.md
**VTD prerequisites needed updating. Same with the module 2 demo**
- Prerequisites for MDE roles and device groups match the SC-200 labs now
- Module 2 demo matched SC-200 lab
-
> Updated VTD demo prerequisites & module 2 demo

- Instructions/VTD_Demos/00-prerequisites.md
**updated module numbering**
- updated module numbering
-
-
> Minor update to VTD demo prerequisites

- Instructions/VTD_Demos/07-perform-threat-hunting-microsoft-sentinel.md
**Hunting query entity mapping was missing steps**
- updated steps for hunting entity mapping
-
-
> Updated custom hunting query entity mapping

- Instructions/VTD_Demos/00-prerequisites.md
**grammar and spelling update**
- create to created
-
-
> minor grammar fix to VTD demo task

- Instructions/.vscode/settings.json
- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/07-perform-threat-hunting-microsoft-sentinel.md
**renumbered attacks and added a completion message**
- renumbered attacks in prerequisites
- added demo completion message
-
> minor change to prerequisites and demo 7

- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Do_Not_Use_Temporary_Issue_Connect_Threat_Intel.md
**Taxii connector fails to connect with already exists or inputs not valid error**
**[Link related Github Issue** 🢂 Fixes # 109
- Renamed lab
- add do not use message
-
> Module 6 lab exercise 4 not working - renamed lab and added message

- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Do_Not_Use_Temporary_Issue_Connect_Threat_Intel.md
**Fixed typo**
- Fixed typo
-
-
> Fixed typo

- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
Small changes in various module labs either for learner clarity or because of Azure portal changes.
> Various small changes for clarity or because of Azure portal changes in various modules

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- M1-Ex1: Updating wording to allow continuity after an error
- M1-Ex1: Separated workspace creation in a new task
- M2-Ex1: Separated some individual instructions and added clarifications
- M2-Ex2: Added expectation Note on when to do the exercise, separated the investigation in a new task
- M3-Ex1: Updated new portal and Arc installation behavior
- M3-Ex2: Removed feedback steps
- M4-Ex1: Added trailing spaces to table names so they can be easily copied to the Logs query window
> Multiple labs update

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
**Changes to LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint and Lab8_Ex1 bug fix**
**Link related Github Issue** 🢂 Fixes #117 
- Fixed issue 117
- Fixed a typo
- Added note to lab
> Changes to LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint and Lab8_Ex1 bug fix

- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
**Updates for PRs 119, 120 & 121 from [awillslo](https://github.com/MicrosoftLearning/SC-200T00A-Microsoft-Security-Operations-Analyst/issues?q=is%3Apr+author%3Aawillslo)**
- Fix Lab 7 EX1, EX3 & EX7
-
-
> Updates to module 7 labs per awillslo

- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
**Responded to issue #122 **
**Link related Github Issue** 🢂 Fixes #122
- Updated task 3 to be consistent with lab 3 ARC onboarding steps
-
-
> Update lab 6 exercise 2 task 3 - onboarding with ARC

- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
Updated per issue #127
**Fixes #127**
- Fixed typo
- Updated folder for Teams Playbook
-
> Fixed lab 7 ex 2 playbook file location and a typo

- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex10_Workbooks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex4_Entity_Behavior.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
**Link related Github Issue** 🢂 None
- Fixed formatting issues in Lab 5, changed instruction for threat indicators, added timing.
- Fixed formatting issues in Lab 6, added legacy Log Analytics agent info.
- Fixed formatting issues in Lab 7, minor portal changes for roles and rule creation, updated queries.
- Fixed formatting issues in Lab 8, updated queries for hunting.
> Minor updates to labs 5, 6, 7 & 8

- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
**No issues**
- Moved KQL search and where operators before let statement
-
-
> Reordered Task 1 moved let statement after search and where operators

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Do_Not_Use_Temporary_Issue_Connect_Threat_Intel.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex10_Workbooks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex4_Entity_Behavior.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex5_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
- readme.md
**Revised lab titles to align with Learn nomenclature**
##N/A
- Revised lab titles
-
-
> Lab titles revised for Learn nomenclature update 

- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
**No options to select Auto provisioning from the Settings Defender plans**
##133
**Link related Github Issue** 🢂 Fixes #133 
- Corrected spelling error
- Fixed the instructions as the interface changed (No options to select Auto provisioning from the Settings Defender plans0
-
> Fixed a typo and updated task 3 per issue #133

- Allfiles/SC200_module4_KQL_scripts.txt
- Reordered text doc lab exercises to match labs
- Revised per awilslo PR
-
> Renumbered & revised to match lab order per awillslo PR on main branch

- Allfiles/SC200_module4_KQL_scripts.txt
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
**Fixes issue #140**
**Link related Github Issue** 🢂 Fixes #140 
- Updated instructions due to changes in LA Demo environment
- Updated text file due to changes in LA Demo environment
-
> Updated KQL in txt and instructions per issue #140

- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
**Link related Github Issue** 🢂 Fixes #144. (Include issue number after #)
- Updated the connector name with "Common Event Format (CEF) via Legacy Agent"
> Learning Path 6 - Lab 1 - Exercise 3

- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
To make the documentation adhere to the defender environment, we should use use **Submit** instead of **Save**
Not really worthy of an issue.
- [ x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝
- a single word update.
> Update from save to submit

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Do_Not_Use_Temporary_Issue_Connect_Threat_Intel.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex10_Workbooks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex4_Entity_Behavior.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex5_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
- LP1-Ex1-M365Defender: Add hint to do guided tours while waiting.
- LP2-Ex1-MDE: Moved detection test to Ex02. Added updated GUI steps. Changed messaging for device group.
- LP2-Ex2-MDEAttacks: Added detection test from Ex01. Reordered task numbers. Updated GUI additional steps.
- LP3-Ex1-MDC: Added exception error case while enable MDC. Added GUI updates wording. Remove GUI step.
- LP3-Ex2-MDCThreats: Added a Regulatory  compliance standard. Assigned an owner to a recommendation. Clarify sample alerts process.
- LP4-Ex1-KQL: Query reformatting. Replaced Location (PII) queries with AuthenticationDetails.
- LP5-Ex1-Sentinel: Change domain name to a Microsoft's example. Minor typos.
- LP6-Ex1-Connectors: Removed Azure AD permission dependencies (includes the Azure AD, IdProt and M365 …
> Lab adaptation to remove Global Admin dependencies and other fixes.

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Do_Not_Use_Temporary_Issue_Connect_Threat_Intel.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex10_Workbooks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex4_Entity_Behavior.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
Fixes numerous issues
**Link related Github Issue** 🢂 Fixes #154, #152, #151, #150.
- fixes issues
- Removes dependency on Global Admin
- Most labs have changes
> Many fixes and lab updates to reduce the need for Global Admin

- Allfiles/SC200_module4_KQL_scripts.txt
- modified text file to match labs
-
-
> Updated text file to match lab KQL statements

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
> Added terms of use note for M365 tenant = to first lab

- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
No issues
- Updated MDE lab instructions for onboarding due to browser blocking
- Updated text per Acrolinx
-
> Updates per UI changes and Acrolinx.

- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
No issues. MD formatting fix.
- Fixed formatting of MD tip.
-
-
> Fixed "TIP" note formatting.

- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
**Link related Github Issue** 🢂 Fixes #160, #161 and #162 (Include issue number after #)
- Added owner permission to subscription.
- Removed WIN2 dependency and using WINServer instead.
- Correction of minor typos.
> Added owner permission to subscription, removed WIN2 dependency, minor typos.

- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
> Changed table column titles to upper case

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
*Fixes bug 169 - new process to prepare Microsoft 365 Defender workspace**
**Link related Github Issue** 🢂 Fixes #169 
- New lab steps to prepare the m365 workspace
-
-
> Updated process to prepare Microsoft 365 Defender workspace

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
**Link related Github Issue** 🢂 Fixes #176, 178, 181, 184, 186
- LAB_AK_01_Lab1_Ex1_Explore_M365_Defender – Updated Task 2 per UI changes
- LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint – Updated per UI changes
- LAB_AK_02_Lab1_Ex2_Mitigate_Attacks – Updated per UI changes
- LAB_AK_03_Lab1_Ex1_Enable_Defender – Fixed typo and updated Task 5 to use AMA and DCR
- LAB_AK_04_Lab1_Ex1_KQL – Updated formatting for queries
- LAB_AK_05_Lab1_Ex1_Deploy_Sentinel – Updated per UI changes and updated KQL formatting for queries
- LAB_AK_06_Lab1_Ex1_Connect_Services – Updated wording for Task 3
- LAB_AK_06_Lab1_Ex1_Connect_Services – Updated Tasks 2 & 3 to use Content Hub …
> Multiple updates to all labs per issues 

- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
No issues
- Changed *Common Event Format* to *Syslog*
-
-
> Fixed misnamed instruction step

- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex6_Perform_Attacks.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
Updates to UI and processes
**Link related GitHub Issue** 🢂 Fixes #189 and #191 
- added new steps for Defender for Cloud connector
- Revised and updated automation rule steps
-
> Lab 06 Ex1 and Lab 07 Ex7 updates

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
**LAB_AK_01_Lab1_Ex1_Explore_M365_Defender**
**Link related Github Issue** 🢂 Fixes #194 
- fix issue #194 
-
-
> Fixes issue #194 LAB_AK_01_Lab1_Ex1_Explore_M365_Defender

- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
**LAB_AK_03_Lab1_Ex1_Enable_Defender: Azure Arc GUI Changes**
**Link related Github Issue** 🢂 Fixes #201 .
- Change the naming used by Azure Arc in the Azure Portal.
> Azure Arc GUI changes

- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
**Link related Github Issue** 🢂 Fixes #200 
- Disable Automanage on task 1.
-
-
> Updated LAB_AK_06_Lab1_Ex2_Connect_Windows per issue #200

- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
**Fix issue #203**
**Link related Github Issue** 🢂 Fixes #203 
- Fix issue #203
-
-
> Revised section per bug issue #203

- Instructions/VTD_Demos/00-prerequisites.md
**Prerequisites out of date**
- Updated and commented out unused sections
-
-
> Updated prerequisites with current lab content

- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/01-mitigate-threats-microsoft-365-defender.md
- Instructions/VTD_Demos/02-mitigate-threats-defender-for-endpoint.md
- Instructions/VTD_Demos/05-configure-your-microsoft-sentinel-environment.md
- Instructions/VTD_Demos/06-create-detections-perform-investigations-microsoft-sentinel.md
**More FY24 VTD demo and prerequisite updates**
- VTD prerequisites 
- VTD demos
-
> Updates to VTD demo prerequisites and demos

- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/VTD_Demos/02-mitigate-threats-defender-for-endpoint.md
- Instructions/VTD_Demos/04-create-queries-for-microsoft-sentinel-using-kql.md
**Fixes issue #211 **
**Link related Github Issue** 🢂 Fixes #211 . (Include issue number after #)
- VTD KQL demo
- resolve issue #211 
-
> Remarked out fileless attack to fix issue #211 and updated KQL VTD demo.

- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex3_Connect_Linux.md
**Fixes issue #208 **
**Link related Github Issue** 🢂 Fixes #208 . (Include issue number after #)
- revised instructions
-
-
> fixing issue #208 Copy paste from former tasks

- Instructions/Labs/LAB_AK_07_Lab1_Ex2_Playbook.md
Followup to #209.
Learning Path 7 - Lab 1 - Exercise 2 - Create a Playbook
Task 3: Update a Playbook in Microsoft Sentinel
Step: 6
Update playbook name at the above step to match other steps.
This step was the subject of a customer report; the change made in this commit will resolve their reported issue. Thank you for lab updates.
> LAB_AK_07_Lab1_Ex2: Update playbook name at Task 3 step 6

- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
**Link related Github Issue** 🢂 Fixes #228 . (Include issue number after #)
- Fixes problem of restore operation consuming Azure Pass credits
-
-
> Fixes issue #228 Billing for Search Job and Data Restore

- Instructions/VTD_Demos/06-create-detections-perform-investigations-microsoft-sentinel.md
- Added NRT rule
- Corrected grammar
-
> Added an NRT rule demo to VTD demos

- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/02-mitigate-threats-defender-for-endpoint.md
**235 and 243**
**Link related Github Issue** 🢂 Fixes #235 and #243. (Include issue number after #)
- New attacks to replace simulations and tutorials
- Updated for MDC compliance UI changes
- Various clean ups
> Fixes issues #235 and #243

- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
**Replaced attacks with a note and link to interactive guide**
- replaced attacks with a temporary note
-
-
> Replaced attacks with a note and link to interactive guide

- Instructions/Labs/LAB_AK_02_Lab1_Ex2_Mitigate_Attacks.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex1_Connect_Services.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex2_Connect_Windows.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
**Link related Github Issue** 🢂 Fixes #236 #245 #249 #250. (Include issue number after #)
- Resolved several issues
- Updated lab 03 for UI changes
-
> Closed issues 236, 245, 249 and 250

- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Defender_XDR.md
> Fixed mistake and revised per Acrolinx

- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Defender_XDR.md
- Fixed additional copy paste mistakes
-
-
> Fixed additional copy paste mistakes

- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
**Updated lab instructions and fixed bug #205 Mod 07 Lab 1 Ex 7 Create Detections )**
**Link related Github Issue** 🢂 Fixes #205 . (Include issue number after #)
- Updated instructions
-  fixed bug #205
-
> Updated lab instructions and fixed bug #205 Mod 07 Lab 1 Ex 7 Create Detections 

- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Defender_XDR.md
**No issue**
- Added missing word
-
-
> Added missing word.

- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
**Lab 07 Exercise 3**
- Updated lab steps
-
-
> Updated lab for new Azure Cloud Shell storage account process options

- Allfiles/SC200_module4_KQL_scripts.txt
- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
**Link related Github Issue** 🢂 Fixes #284  . (Include issue number after #)
- Revised KQL query
- Revised KQL queries text file
-
> Resolves issue #284 Learning Path 4 - Lab 1 - Exercise 1 - Create queries for Microsoft Sentinel using Kusto Query Language (KQL)

- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
**Link related Github Issue** 🢂 Fixes #260  . (Include issue number after #)
- Revised instructions to use parsers deployed with new Sentinel instance
-
-
> Resolves issue#260 ASIM parsers lab

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_02_Lab1_Ex1_Deploy_Defender_Endpoint.md
**No issues just minor revisions**
- Revised instructions
- Revised grammar per Acrolinx
-
> Grammar (Acrolinx) and fine-tuning updates.

- Instructions/Labs/LAB_AK_08_Lab1_Ex2_Notebooks.md
**Learning Path 8 - Lab 1 - Exercise 2 - Notebooks lab no longer working due a change in MSTICpy**
**Link related Github Issue** 🢂 Fixes #290  . (Include issue number after #)
- Revised instructions to correct issue
- Ran Acrolinx
-
> Resolves issue - Learning Path 8 - Lab 1 - Exercise 2 - Notebooks lab no longer working due a change in MSTICpy

- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Fixed MD code remark error
-
-
> Fixed MD code error

- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Defender_XDR.md
**No specific issue**
- Updated note on lab 3
- Added note to lab 6
-
> Minor updates to Lab 3 and Lab 6

- Instructions/Labs/LAB_AK_01_Lab1_Ex1_Explore_M365_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex1_Enable_Defender.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex2_Azure_Defender.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex1_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Defender_XDR.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex3_Scheduled_Query.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex4_Entity_Behavior.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex7_Detections.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex8_Investigate.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex9_ASIM.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex1_Hunting.md
**Closes issue #300 and many minor UI changes**
**Link related Github Issue** 🢂 Fixes #300 . (Include issue number after #)
- Close issue #300 
- Fixes many formatting and UI changes
-
> Closes issue #300 and many minor UI changes

- Instructions/Labs/LAB_AK_06_Lab1_Ex4_Connect_Defender_XDR.md
- Instructions/Labs/LAB_AK_07_Lab1_Ex1_Security_Rule.md
**Link related Github Issue** 🢂 Fixes #299 . (Include issue number after #)
- added notes
-
-
> Closes issue: Lab 7  Not able to create an Microsoft Incident creation rule #299

- Instructions/VTD_Demos/00-prerequisites.md
- Instructions/VTD_Demos/01-mitigate-threats-microsoft-365-defender.md
- Instructions/VTD_Demos/03-mitigate-threats-defender-cloud.md
- Instructions/VTD_Demos/05-configure-your-microsoft-sentinel-environment.md
- Instructions/VTD_Demos/06-create-detections-perform-investigations-microsoft-sentinel.md
- Instructions/VTD_Demos/07-perform-threat-hunting-microsoft-sentinel.md
- Updated prerequisites
- Added Unified Security Operations demo
-
> Updates to VTD demos for VTD-5002-FY25

- Instructions/Labs/LAB_AK_04_Lab1_Ex1_KQL.md
- Added note on SigninLogs table
-
-
> Added note on SigninLogs table

- Instructions/Labs/LAB_AK_08_Lab1_Ex03_Connect_Linux.md
**Link related Github Issue** 🢂 Fixes #305 . (Include issue number after #)
- Revised instructions but more revisions needed.
-
-
> Close issue #305 - LP6-LAB1-EX.3: Unnecessary permissions requested

- Allfiles/Bicep/Sentinel.bicep
> Uncommented sections of Bicep template 

- Allfiles/Bicep/Sentinel.bicep
- Added code to user identity script
- Merged branch 'master' of
-
-
> Added code to script user identity

- Instructions/Labs/LAB_AK_02_Lab1_Ex01_Explore_Copilot_Security.md
- Image links were not displaying correctly
- Added note on PowerShell alert timestamp
-
> Revised image links and added a note.

- Allfiles/attacksim.ps1
- Instructions/Labs/LAB_AK_04_Lab1_Ex02_Mitigate_Attacks.md
> Fixed Lab 04 step numbering

- Allfiles/Bicep/Sentinel.bicep
- Instructions/Labs/LAB_AK_08_Lab1_Ex02_Connect_Windows.md
- Revised Bicep template per ALH
- Updated lab 08 instructions
-
> Revised Bicep template & updated lab 08 instructions

- Allfiles/Bicep/Sentinel.bicep
- Added comment to template
-
-
> Added comment to template

- Allfiles/AttackScript.ps1
- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex02_Connect_Windows.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex03_Connect_Linux.md
- Revised AttackScript and Lab 08 instructions
-
-
> Revised AttackScript and Lab 08 instructions

- Instructions/Labs/LAB_AK_05_Lab1_Ex01_Enable_MDC.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex02_Connect_Windows.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex03_Connect_Linux.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex01_Security_Rule.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex02_Playbook.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex03_Scheduled_Query.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex04_Entity_Behavior.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex05_Attacks.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex07_Detections.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex08_Investigate.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex09_ASIM.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex10_Workbooks.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex11_Content_Management.md
- Instructions/Labs/LAB_AK_10_Lab1_Ex01_Hunting.md
- Instructions/Labs/LAB_AK_10_Lab1_Ex02_Notebooks.md
- Pre-installed Azure Arc on WINServer
- Added notes on pre-deploying Sentinel
- Revised text
> Pre-installed Azure Arc on WINServer & revised text

- Instructions/Labs/LAB_AK_05_Lab1_Ex01_Enable_MDC.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex05_Attacks.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex06_Perform_Attacks.md
- Instructions/Labs/LAB_AK_10_Lab1_Ex01_Hunting.md
- Reused Azure Arc connect instructions
- Added notes
-
> Revised instructions to use pre-deployed Azure Arc and added notes.

- Instructions/Labs/LAB_AK_07_Lab1_Ex01_Deploy_Sentinel.md
- Revised instructions for task 5 due to UI changes.
-
-
> Updated Lab 07 task 5 on TI per new UI

- Instructions/Labs/LAB_AK_05_Lab1_Ex01_Enable_MDC.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex02_Explore_MDC.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex03_Connect_Linux.md
- Revised instructions to prevent error messages
-
-
> Revised Lab 05 instructions

- Instructions/Labs/LAB_AK_09_Lab1_Ex02_Playbook.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex03_Scheduled_Query.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex06_Perform_Attacks.md
- Instructions/Labs/LAB_AK_10_Lab1_Ex01_Hunting.md
- Added note Lab 09 to use preview portal
- Fixed blocking issues
-
> Resolve blocking issues in Lab 10 instructions

- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
- Updated task 2 instructions
-
-
> Revised Lab 08 exercise 1, task 2 instructions

- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
> Revised Lab 08 exercise 1 page formatting

- Allfiles/Bicep/sentinelParams.bicepparam
- Instructions/Labs/LAB_AK_05_Lab1_Ex01_Enable_MDC.md
- Instructions/Labs/LAB_AK_05_Lab1_Ex02_Explore_MDC.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
- Removed the Threat Intelligence solution from Bicep parameters
- Fixed typos
- Added note
- Fixed typos 
-
> Removed Threat Intelligence solution, fixed typos and added note

- Instructions/Labs/LAB_AK_06_Lab1_Ex01_KQL.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex03_Scheduled_Query.md
- MD and missing word fixed in lab 6
- Revised lab 9 per Q&A feedback
- Ran Acrolinx
-
> Revised labs 6 and 9 per Q&A feedback

- Instructions/Labs/LAB_AK_01_Lab1_Ex01_Explore_Defender_XDR.md
- Instructions/Labs/LAB_AK_03_Lab1_Ex01_Explore_Purview_Audit.md
- Revised labs 01 and 02 MD and instructions
-
-
> Revised Labs 01 and 02 MD and instructions

- Instructions/Labs/LAB_AK_08_Lab1_Ex03_Connect_Linux.md
- Updated lab instructions
-
-
> Revised Lab 08 Exercise 3 instructions per updated Microsoft Sentinel UI

- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
- Instructions/Labs/LAB_AK_09_Lab1_Ex03_Scheduled_Query.md
> Revised instructions for the Azure Activity connector.

- Instructions/Labs/LAB_AK_07_Lab1_Ex01_Deploy_Sentinel.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex02_Connect_Windows.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex03_Connect_Linux.md
- Updates to Lab 07
- Updates to Lab 08
-
> Revisions per MTT Q&A

- Instructions/VTD_Demos/00-prerequisites.md
- Removed and revised instructions to remove Azure Pass references from the VTD demo prerequisites.
- Ran Acrolinx
-
> Removed Azure Pass references from VTD demo prerequisite instructions

- Instructions/Labs/LAB_AK_03_Lab1_Ex01_Explore_Purview_Audit.md
- Added "Alert" note with instruction to work around Audit recording issue.
-
-
> Added alert note to work around Purview Audit recording issue.

- Instructions/Labs/LAB_AK_03_Lab1_Ex01_Explore_Purview_Audit.md
> Testing revised note format.

- Instructions/Labs/LAB_AK_04_Lab1_Ex01_Deploy_Defender_Endpoint.md
… is Windows 11 issue #367
**Link related Github Issue** 🢂 Fixes #367 . (Include issue number after #)
- Changed OS and note.
-
-
> Fix issue #367

- Instructions/Labs/LAB_AK_01_Lab1_Ex01_Explore_Defender_XDR.md
**Link related Github Issue** 🢂 Fixes #379 . (Include issue number after #)
- Fixed
-
-
> Fixed issue #3799

- Instructions/Labs/LAB_AK_04_Lab1_Ex01_Deploy_Defender_Endpoint.md
**Link related Github Issue** 🢂 Fixes #372 . (Include issue number after #)
- Revised lab for new Unified RBAC
-
-
> Fix M00-LAB00: QUICK_DESCRIPTION #372

- Instructions/Labs/LAB_AK_04_Lab1_Ex01_Deploy_Defender_Endpoint.md
**Small Typo**
- Small typo fix
> Fixed typo on instructions

- Instructions/Labs/LAB_AK_09_Lab1_Ex02_Playbook.md
- Revised instruction for clarity
-
-
> Updated this lab for clarity and ran Acrolinx

- Instructions/Labs/LAB_AK_09_Lab1_Ex07_Detections.md
- Added note on WINServer update
- Swapped correct playbook into table
-
> Updated to resolve issue with 4732 event and incorrect playbook

- Instructions/Labs/LAB_AK_06_Lab1_Ex01_KQL.md
- Instructions/Labs/LAB_AK_10_Lab1_Ex02_Notebooks.md
**Link related Github Issue** 🢂 Fixes #391 . (Include issue number after #)
- Added note on LA Demo transition
- Revised lab 10 Python kernel to 3.10
-
> Added note on LA Demo and updated lab 10 Python kernel

- Instructions/Labs/LAB_AK_08_Lab1_Ex04_Connect_Defender_XDR.md
- Revised simulation instructions.
-
-
> Revised simulation instructions for launching Sentinel

- Allfiles/Bicep/sentinelParams.bicepparam
- Added Defender XDR connector
-
-
> Added Defender XDR connector

- Instructions/Labs/LAB_AK_08_Lab1_Ex01_Connect_Services.md
**Link related Github Issue** 🢂 Fixes #415 . (Include issue number after #)
- Made changes to instructions for clarity
- Ran Acrolinx
-
> Clarified instructions to enable bi-directional sync

- Instructions/Labs/LAB_AK_07_Lab1_Ex01_Deploy_Sentinel.md
…pace every time Sentinel is opened #413
**Link related Github Issue** 🢂 Fixes #413 . (Include issue number after #)
- Added missing instructions
-
-
> Added missing instructions to fix issue #413

- Instructions/Labs/LAB_AK_02_Lab1_Ex01_Explore_Copilot_Security.md
- Instructions/Labs/LAB_AK_08_Lab1_Ex04_Connect_Defender_XDR.md
- Instructions/Labs/LAB_AK_10_Lab1_Ex01_Hunting.md
**Link related Github Issue** 🢂 Fixes #431  . (Include issue number after #)
- Revised markdown for link to simulation per MTT request.
-
-
> Fixes issue #431
